[package]
name = "buf-yaml-advanced"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = {version = "0.14", features = ["tls-webpki-roots"]}
tonic-prost = "0.14"
tokio = {version = "1.40.0", features = ["full"]}
prost = "0.14"

[build-dependencies]
tonic-buf-build = {path = "../../"}